In [3]:
import numpy as np

In [4]:
# 단위 행렬 만등기
print('3*3 단위 행렬')
print(np.eye(3),end='\n\n')
print('3*5 단위 행렬')
print(np.eye(3,5),end='\n\n')
print('3*5 단위 행렬 시작점이 1')
print(np.eye(3,5,1),end='\n\n')
print('3*5 단위 행렬 시작점이 -1')
print(np.eye(3,5,-1),end='\n\n')

3*3 단위 행렬
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

3*5 단위 행렬
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]

3*5 단위 행렬 시작점이 1
[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]

3*5 단위 행렬 시작점이 -1
[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]



In [5]:
# numpy.arange([start, ]stop, [step, ]dtype=None)
np.arange(12,step=0.5) # 0~12 까지의 1차원 벡터 생서

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5,
       11. , 11.5])

In [6]:
mat=np.arange(24).reshape(4,6) # 4 행 6열 행렬 만들기
print(mat)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [7]:
print(np.diag(mat,1),'\n\n')
print(np.diag(mat,-1))

[ 1  8 15 22] 


[ 6 13 20]


In [8]:
#https://numpy.org/doc/1.19/search.html?q=random&check_keywords=yes&area=default
# np.random.원하는 분포 선택 가능
np.random.normal(0,1,10)

array([-1.17144561,  1.11520642, -0.18120962, -1.59330844, -0.61317484,
        0.17286971,  0.61489504, -0.63987275,  0.97991396, -0.75923481])

axis

1 차원 axis가 하나만 존재 only axis=0

<h3>---------------------------------- -> axis=0</h3>

1 차원에서 2차원으로 가면서 기존 axis ++ 
즉, 가로(행)이 axis 1이 된다.

2 차원 행들이 모여 열이 생김  axis=1 행 axis=0 열

2 차원에서 3차원으로 가면서 기존 axis ++

<h3>----------------------------------  -> axis=1 기존 축 +1</h3> 
<h3>-</h3>
<h3>-</h3>
<h3>-</h3>
-> axis =0 새로운 축

3 차원을 어떻게 말할지 모르겠는데 걍 행열의 집합이라 하자.
3차원 numpy 배열은 (3,4,6) 이런 식으로 되는데
각각 (행렬의 개수 axis=0, 각 행렬의 행의 개수 axis=1, 각 행렬의 열의 개수 axis=2) 이걸 나타낸다.

<h3>----------------------------------  -> axis=1 기존 축 +1</h3> 
<h3>-</h3>
<h3>- 　　　　　　　　　　　　　　 * n 개 즉 새로운 축 axis=0 </h3>
<h3>-</h3>
-> axis =1 기존 축 +1

In [9]:
one_d=np.arange(24)
print(one_d.shape, 'axis 0 = 24')
print(one_d)

(24,) axis 0 = 24
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [10]:
mat=np.arange(24).reshape(4,6)
print(mat.shape,'axis 0 = 4 행의 개수  axis 1 = 6 열의 개수')
print(mat)

(4, 6) axis 0 = 4 행의 개수  axis 1 = 6 열의 개수
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [26]:
print('axis=0')
print(mat.sum(axis=0),end='\n\n')
print('이것들의 합')
print(mat[:,0],',',mat[:,1],',',mat[:,2],',',mat[:,3],',',mat[:,4],',',mat[:,5], end='\n\n')
print('                                ==                                               ')
print(mat[:,0:1])
print('axis 가 0이니 axis=0 방향으로 더함')
print('--------------------------------------------------------------------------------------')
print('axis=1')
print(mat.sum(axis=1))
print('이것들의 합')
print(mat[2,3:4],',',mat[1,:],',',mat[2,:],',',mat[3,:],end='\n\n')
print('axis 가 1이니 axis=1 방향으로 더함')

axis=0
[36 40 44 48 52 56]

이것들의 합
[ 0  6 12 18] , [ 1  7 13 19] , [ 2  8 14 20] , [ 3  9 15 21] , [ 4 10 16 22] , [ 5 11 17 23]

                                ==                                               
[[ 0]
 [ 6]
 [12]
 [18]]
axis 가 0이니 axis=0 방향으로 더함
--------------------------------------------------------------------------------------
axis=1
[ 15  51  87 123]
이것들의 합
[15] , [ 6  7  8  9 10 11] , [12 13 14 15 16 17] , [18 19 20 21 22 23]

axis 가 1이니 axis=1 방향으로 더함


In [19]:
mat[3,1:3]

array([19, 20])

In [38]:
three_d=np.arange(24).reshape(2,3,4)
print(three_d.shape,'axis 0 = 2 행렬의 개수 axis 1 = 3 행의 개수  axis 2 = 4 열의 개수','\n\n')
print(three_d)

(2, 3, 4) axis 0 = 2 행렬의 개수 axis 1 = 3 행의 개수  axis 2 = 4 열의 개수 


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [52]:
print('axis=0')
print(three_d.sum(axis=0),end='\n\n')
print('아래 것들의 합')
print(three_d[:,0],end='\n\n')
print(three_d[:,1],end='\n\n')
print(three_d[:,2])

axis=0
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]

아래 것들의 합
[[ 0  1  2  3]
 [12 13 14 15]]

[[ 4  5  6  7]
 [16 17 18 19]]

[[ 8  9 10 11]
 [20 21 22 23]]


In [63]:
print('axis=1')
print(three_d.sum(axis=1),end='\n\n')
print('아래 것들의 합')
print(three_d[0,:,0],three_d[0,:,1],three_d[0,:,2],three_d[0,:,3])
print(three_d[1,:,0],three_d[1,:,1],three_d[1,:,2],three_d[1,:,3])

axis=1
[[12 15 18 21]
 [48 51 54 57]]

아래 것들의 합
[0 4 8] [1 5 9] [ 2  6 10] [ 3  7 11]
[12 16 20] [13 17 21] [14 18 22] [15 19 23]


In [70]:
print('axis=2')
print(three_d.sum(axis=2),end='\n\n')
print('아래 것들의 합')
print(three_d[0,0,],three_d[0,1,],three_d[0,2,])
print(three_d[1,0,],three_d[1,1,],three_d[1,2,])

axis=2
[[ 6 22 38]
 [54 70 86]]

아래 것들의 합
[0 1 2 3] [4 5 6 7] [ 8  9 10 11]
[12 13 14 15] [16 17 18 19] [20 21 22 23]


<h1>numpy slicing!!!!</h1>


In [72]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [80]:
a[2]

2

In [81]:
b=np.arange(24).reshape(3,8)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [86]:
# 2차원 slicing은 [원하는 행, 원하는 열] 식이다.
# 위 행렬에서 [[11,12,13],[19,20,21]]을 뽑아보자
b[1:3,3:6]

#해설 : 11,12,13  19,20,21은  1번 행렬, 2번 행렬에 위치해있으므로 1부터 3까지(미만) 1:3
# 또한 각 행에서 3번째 부터 6번째까지 있으니 3:6

array([[11, 12, 13],
       [19, 20, 21]])

In [88]:
b[:,0] # 모든 행 , 0번째 열

array([ 0,  8, 16])

In [89]:
b[1,:] # 첫번쨰 열 , 모든 열

array([ 8,  9, 10, 11, 12, 13, 14, 15])

In [90]:
c=np.arange(36).reshape(3,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [91]:
# 3차원 slicing은 [원하는 행렬, 원하는 행, 원하는 열]
# 위 행렬에서 [1,5,9] [13,17,21] [25,29,33]을 뽑아 보자
c[:,:,1] # 모든  행렬, 모든 행, 첫번째 행

array([[ 1,  5,  9],
       [13, 17, 21],
       [25, 29, 33]])

<h1> broadcasting </h1>
알아서 잘 맞춰 준다.

In [93]:
broad_np=np.arange(12).reshape(4,3)
broad_np

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [94]:
broad_np+10

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [96]:
broad_np+np.array([10,10,10])

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

<h1>np.where</h1>

sql where 처럼 조건에 맞는 값 뽑아오기

In [98]:
where_np=np.arange(12)
where_np

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [99]:
np.where(where_np>5,100,-100) # np.where(조건, True, False)

array([-100, -100, -100, -100, -100, -100,  100,  100,  100,  100,  100,
        100])

In [100]:
np.where(where_np>5) #조건만 명

(array([ 6,  7,  8,  9, 10, 11], dtype=int64),)